# Mixed-effects models for eye-emdm behavioral data using brms
# Reads CSVs from output/behavior/stats generated by analyze_behavior.py

suppressPackageStartupMessages({
  library(brms)
  library(loo)
  library(readr)
  library(dplyr)
  library(broom.mixed)
})

project_root <- getwd()
stats_dir <- file.path(project_root, "output", "behavior", "stats")

ensure_dir <- function(path) {
  if (!dir.exists(path)) dir.create(path, recursive = TRUE)
}

# brms sampling configuration
brms_chains <- 4
brms_iter <- 2000
brms_cores <- min(4, parallel::detectCores())
brms_seed <- 2026
exp_version <- "brms"

save_model_outputs <- function(name, fit) {
  # Text summary
  summ <- summary(fit)
  summ_txt <- capture.output(summ)
  writeLines(summ_txt, file.path(stats_dir, paste0(name, "_summary.txt")))
  # Tidy coefficients
  tidy_df <- tryCatch({
    broom.mixed::tidy(fit, effects = "fixed")
  }, error = function(e) {
    NULL
  })
  if (!is.null(tidy_df)) {
    readr::write_csv(tidy_df, file.path(stats_dir, paste0(name, "_summary.csv")))
  }
}

ensure_dir(stats_dir)

# 1) accuracy ~ 1 + (1 | subject)
acc_path <- file.path(stats_dir, "accuracy_df.csv")
if (file.exists(acc_path)) {
  d1 <- readr::read_csv(acc_path, show_col_types = FALSE) %>%
    mutate(subject = as.factor(subject))
  if (nrow(d1) > 0) {
    m1 <- brm(
      correct_bin ~ 1 + (1|subject),
      data = d1,
      family = bernoulli(link = "logit"),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("accuracy_mixed_logistic", m1)
  }
}

# 1b) spatial/location accuracy - chance (1/6)
spat_path <- file.path(stats_dir, "spatial_accuracy_df.csv")
if (file.exists(spat_path)) {
  d_spat <- readr::read_csv(spat_path, show_col_types = FALSE) %>%
    mutate(subject = as.factor(subject)) %>%
    group_by(subject, game) %>%
    summarise(spatial_acc_centered = mean(spatial_correct_bin) - 1/6, .groups = "drop")
  if (nrow(d_spat) > 0) {
    m1b <- brm(
      spatial_acc_centered ~ 1 + (1|subject),
      data = d_spat,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("spatial_accuracy_centered_mixed", m1b)
  }
}

# 2) choice ~ 1 + true_offer_value + (1 + true_offer_value | subject)
ctv_path <- file.path(stats_dir, "choices_all.csv")
if (file.exists(ctv_path)) {
  d_choice_both <- readr::read_csv(ctv_path, show_col_types = FALSE) %>%
    mutate(subject = as.factor(subject)) %>%
    tidyr::drop_na(choice, true_offer_value, recalled_offer_value) %>%
    mutate(
      choice_bin = as.integer(choice),
      true_offer_value_z = as.numeric(scale(true_offer_value)),
      recalled_offer_value_z = as.numeric(scale(recalled_offer_value))
    )

  if (nrow(d_choice_both) > 0) {
    # 2) choice ~ true_offer_value on common rows
    m2 <- brm(
      choice_bin ~ 1 + true_offer_value_z + (1 + true_offer_value_z|subject),
      data = d_choice_both,
      family = bernoulli(link = "logit"),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("choice_true_value_mixed_logistic", m2)

    # 3) choice ~ recalled_offer_value on the same rows
    m3 <- brm(
      choice_bin ~ 1 + recalled_offer_value_z + (1 + recalled_offer_value_z|subject),
      data = d_choice_both,
      family = bernoulli(link = "logit"),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("choice_recalled_value_mixed_logistic", m3)
  }
} else {
  warning("choices_all.csv not found in ", stats_dir, "; falling back to separate datasets.")
  # Fallback: previous behavior using separate datasets
  # 2) choice ~ 1 + true_offer_value + (1 + true_offer_value | subject)
  ctv_path <- file.path(stats_dir, "choice_true_value_df.csv")
  if (file.exists(ctv_path)) {
    d2 <- readr::read_csv(ctv_path, show_col_types = FALSE) %>%
      mutate(subject = as.factor(subject)) %>%
      tidyr::drop_na(choice_bin, true_offer_value) %>%
      mutate(true_offer_value_z = as.numeric(scale(true_offer_value)))
    if (nrow(d2) > 0) {
      m2 <- brm(
        choice_bin ~ 1 + true_offer_value_z + (1 + true_offer_value_z|subject),
        data = d2,
        family = bernoulli(link = "logit"),
        chains = brms_chains,
        iter = brms_iter,
        cores = brms_cores,
        seed = brms_seed
      )
      save_model_outputs("choice_true_value_mixed_logistic", m2)
    }
  }

  # 3) choice ~ 1 + recalled_offer_value + (1 + recalled_offer_value | subject)
  crv_path <- file.path(stats_dir, "choice_recalled_value_df.csv")
  if (file.exists(crv_path)) {
    d3 <- readr::read_csv(crv_path, show_col_types = FALSE) %>%
      mutate(subject = as.factor(subject)) %>%
      tidyr::drop_na(choice_bin, recalled_offer_value) %>%
      mutate(recalled_offer_value_z = as.numeric(scale(recalled_offer_value)))
    if (nrow(d3) > 0) {
      m3 <- brm(
        choice_bin ~ 1 + recalled_offer_value_z + (1 + recalled_offer_value_z|subject),
        data = d3,
        family = bernoulli(link = "logit"),
        chains = brms_chains,
        iter = brms_iter,
        cores = brms_cores,
        seed = brms_seed
      )
      save_model_outputs("choice_recalled_value_mixed_logistic", m3)
    }
  }
}

# Compare predictive performance via 10-fold ELPD (kfold) for choice models
if (exists("m2") && exists("m3")) {
  m2 <- add_criterion(m2, "kfold", K = 10)
  m3 <- add_criterion(m3, "kfold", K = 10)

  elpd_true <- m2$criteria$kfold$pointwise[, 1]
  elpd_mem  <- m3$criteria$kfold$pointwise[, 1]

  elpd_diff <- (elpd_mem - elpd_true)
  elpd_se <- sqrt(length(elpd_diff)) * stats::sd(elpd_diff)

  elpd_df_out <- data.frame(elpd_diff = sum(elpd_diff),
                            se_diff   = elpd_se)
  elpd_raw <- data.frame(elpd_mem = elpd_mem,
                         elpd_true = elpd_true,
                         elpd_diff = elpd_diff)

  readr::write_csv(elpd_df_out, file.path(stats_dir, paste0("choice_elpd_diff_", exp_version, ".csv")))
  readr::write_csv(elpd_raw, file.path(stats_dir, paste0("choice_elpd_diff_raw_", exp_version, ".csv")))
}

# 4a) log(rt) ~ 1 + recalled_total_count + (1 + recalled_total_count | subject)
rt_tot_path <- file.path(stats_dir, "rt_total_recall_df.csv")
if (file.exists(rt_tot_path)) {
  d4a <- readr::read_csv(rt_tot_path, show_col_types = FALSE) %>%
    mutate(subject = as.factor(subject)) %>%
    tidyr::drop_na(log_rt, recalled_total_count)
  if (nrow(d4a) > 0) {
    m4a <- brm(
      log_rt ~ 1 + recalled_total_count + (1 + recalled_total_count|subject),
      data = d4a,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("rt_vs_total_recall_mixed", m4a)
  }
}

# 4b) log(rt) ~ 1 + recalled_offer_count + (1 + recalled_offer_count | subject)
rt_off_path <- file.path(stats_dir, "rt_offer_recall_df.csv")
if (file.exists(rt_off_path)) {
  d4b <- readr::read_csv(rt_off_path, show_col_types = FALSE) %>%
    mutate(subject = as.factor(subject)) %>%
    tidyr::drop_na(log_rt, recalled_offer_count)
  if (nrow(d4b) > 0) {
    m4b <- brm(
      log_rt ~ 1 + recalled_offer_count + (1 + recalled_offer_count|subject),
      data = d4b,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("rt_vs_offer_recall_mixed", m4b)
  }
}

# 5) recall proportion ~ 1 + (1 | subject)
rec_prop_path <- file.path(stats_dir, "recall_prop_df.csv")
if (file.exists(rec_prop_path)) {
  d5 <- readr::read_csv(rec_prop_path, show_col_types = FALSE) %>%
    mutate(subject = as.factor(subject))
  if (nrow(d5) > 0) {
    m5 <- brm(
      recall_prop_centered ~ 1 + (1|subject),
      data = d5,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("recall_prop_centered_mixed", m5)
  }
}

# 6) true associated reward ~ 1 + recalled associated reward + (1 + recalled associated reward | subject)
item_vals_path <- file.path(stats_dir, "item_values_df.csv")
if (file.exists(item_vals_path)) {
  d6 <- readr::read_csv(item_vals_path, show_col_types = FALSE) %>%
    mutate(subject = as.factor(subject)) %>%
    tidyr::drop_na(true_value, recalled_value)
  if (nrow(d6) > 0) {
    m6 <- brm(
      true_value ~ 1 + recalled_value + (1 + recalled_value|subject),
      data = d6,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("true_vs_recalled_value_mixed", m6)
  }
}

# 7) log(rt) ~ 1 + recalled_offer_value_z + recalled_offer_value_z^2 + (1 + recalled_offer_value_z + recalled_offer_value_z^2 | subject)
# and same for true offer value
# Uses choices_all.csv (same data as choice models, with z-scored offer values)
rt_ov_path <- file.path(stats_dir, "choices_all.csv")
if (file.exists(rt_ov_path)) {
  d_rt_ov <- readr::read_csv(rt_ov_path, show_col_types = FALSE) %>%
    mutate(subject = as.factor(subject)) %>%
    tidyr::drop_na(rt, true_offer_value, recalled_offer_value) %>%
    dplyr::filter(rt > 0) %>%
    mutate(
      log_rt = log(rt),
      true_offer_value_z = as.numeric(scale(true_offer_value)),
      recalled_offer_value_z = as.numeric(scale(recalled_offer_value)),
      true_offer_value_z2 = true_offer_value_z^2,
      recalled_offer_value_z2 = recalled_offer_value_z^2
    )

  if (nrow(d_rt_ov) > 0) {
    # 7a) log(rt) ~ recalled offer value (quadratic)
    m7a <- brm(
      log_rt ~ 1 + recalled_offer_value_z + recalled_offer_value_z2 +
        (1 + recalled_offer_value_z + recalled_offer_value_z2|subject),
      data = d_rt_ov,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("rt_vs_recalled_offer_value_quad_mixed", m7a)

    # 7b) log(rt) ~ true offer value (quadratic)
    m7b <- brm(
      log_rt ~ 1 + true_offer_value_z + true_offer_value_z2 +
        (1 + true_offer_value_z + true_offer_value_z2|subject),
      data = d_rt_ov,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("rt_vs_true_offer_value_quad_mixed", m7b)
  }
}

message("Mixed-effects model summaries saved to ", stats_dir)
