# Mixed-effects eye-tracking models for eye-emdm using brms
# Uses CSVs generated by analysis/choice_fixation_proportions.py (duration metric)

suppressPackageStartupMessages({
  library(brms)
  library(readr)
  library(dplyr)
  library(broom.mixed)
})

project_root <- getwd()
stats_dir <- file.path(project_root, "output", "eyegaze", "stats")

ensure_dir <- function(path) {
  if (!dir.exists(path)) dir.create(path, recursive = TRUE)
}

# brms sampling configuration
brms_chains <- 4
brms_iter <- 2000
brms_cores <- min(4, parallel::detectCores())
brms_seed <- 2026

save_model_outputs <- function(name, fit) {
  # Text summary
  summ <- summary(fit)
  summ_txt <- capture.output(summ)
  writeLines(summ_txt, file.path(stats_dir, paste0(name, "_summary.txt")))
  # Tidy coefficients
  tidy_df <- tryCatch({
    broom.mixed::tidy(fit, effects = "fixed")
  }, error = function(e) {
    NULL
  })
  if (!is.null(tidy_df)) {
    readr::write_csv(tidy_df, file.path(stats_dir, paste0(name, "_summary.csv")))
  }
}

ensure_dir(stats_dir)

# Helper to safely read CSV
read_csv_if_exists <- function(path) {
  if (file.exists(path)) {
    readr::read_csv(path, show_col_types = FALSE)
  } else {
    warning("File not found: ", path)
    NULL
  }
}

# ---------- 0) Relevant total fixation time vs chance (trial-level) ----------
# Based on trial-level relevant-only deltas produced by choice_fixation_proportions.py
# File: output/choice_fixation_relevant_trial_deltas_long_duration.csv

rel_long_path <- file.path(project_root, "output", "eyegaze", "stats", "choice_fixation_relevant_trial_deltas_long_duration.csv")

rel_long_df <- read_csv_if_exists(rel_long_path)

if (!is.null(rel_long_df)) {
  rel_long_df <- rel_long_df %>%
    mutate(subject = as.factor(subject))

  # Collapse over valence to get total relevant proportion per trial and its
  # deviation from chance. There are two rows per trial (rel_pos, rel_neg).
  rel_total_trial <- rel_long_df %>%
    group_by(subject, game, trial_number, decision_label) %>%
    summarise(
      prop_relevant = sum(prop, na.rm = TRUE),
      chance_relevant = sum(chance, na.rm = TRUE),
      delta_relevant = sum(delta_from_chance, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    tidyr::drop_na(delta_relevant)

  if (nrow(rel_total_trial) > 0) {
    m0 <- brm(
      delta_relevant ~ 1 + (1 | subject),
      data = rel_total_trial,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("eye_relevant_total_delta_mixed", m0)
  }
}

# ---------- 1) Relevant-only relsign4: delta_from_chance ~ decision * valence ----------
# Mirrors: Trial-level Relevant-only MixedLM (delta ~ decision*valence + (1|subject))

if (!is.null(rel_long_df)) {
  d_rel_delta <- rel_long_df %>%
    mutate(
      subject = as.factor(subject),
      decision_label = as.factor(decision_label),
      valence_label = as.factor(valence_label)
    ) %>%
    tidyr::drop_na(delta_from_chance, decision_label, valence_label)

  if (nrow(d_rel_delta) > 0) {
    m_rel_delta <- brm(
      delta_from_chance ~ 1 + decision_label * valence_label + (1 + decision_label * valence_label | subject),
      data = d_rel_delta,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("eye_relsign4_relevant_delta_mixed", m_rel_delta)
  }
}

# ---------- 2) Relevant-only relsign4: prop ~ decision * valence ----------
# Mirrors: Trial-level Relevant-only MixedLM (prop ~ decision*valence + (1|subject))

if (!is.null(rel_long_df)) {
  d_rel_prop <- rel_long_df %>%
    mutate(
      subject = as.factor(subject),
      decision_label = as.factor(decision_label),
      valence_label = as.factor(valence_label)
    ) %>%
    tidyr::drop_na(prop, decision_label, valence_label)

  if (nrow(d_rel_prop) > 0) {
    m_rel_prop <- brm(
      prop ~ 1 + decision_label * valence_label + (1 + decision_label * valence_label | subject),
      data = d_rel_prop,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("eye_relsign4_relevant_prop_mixed", m_rel_prop)
  }
}

# ---------- 3) Irrelevant-only relsign4: delta_from_chance ~ decision * valence ----------
# Mirrors: Trial-level Irrelevant-only MixedLM (delta ~ decision*valence + (1|subject))

irr_long_path <- file.path(project_root, "output", "eyegaze", "stats", "choice_fixation_irrelevant_trial_deltas_long_duration.csv")

irr_long_df <- read_csv_if_exists(irr_long_path)

if (!is.null(irr_long_df)) {
  d_irr_delta <- irr_long_df %>%
    mutate(
      subject = as.factor(subject),
      decision_label = as.factor(decision_label),
      valence_label = as.factor(valence_label)
    ) %>%
    tidyr::drop_na(delta_from_chance, decision_label, valence_label)

  if (nrow(d_irr_delta) > 0) {
    m_irr_delta <- brm(
      delta_from_chance ~ 1 + decision_label * valence_label + (1 + decision_label * valence_label | subject),
      data = d_irr_delta,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("eye_relsign4_irrelevant_delta_mixed", m_irr_delta)
  }
}

# ---------- 4) Irrelevant-only relsign4: prop ~ decision * valence ----------
# Mirrors: Trial-level Irrelevant-only MixedLM (prop ~ decision*valence + (1|subject))

if (!is.null(irr_long_df)) {
  d_irr_prop <- irr_long_df %>%
    mutate(
      subject = as.factor(subject),
      decision_label = as.factor(decision_label),
      valence_label = as.factor(valence_label)
    ) %>%
    tidyr::drop_na(prop, decision_label, valence_label)

  if (nrow(d_irr_prop) > 0) {
    m_irr_prop <- brm(
      prop ~ 1 + decision_label * valence_label + (1 + decision_label * valence_label | subject),
      data = d_irr_prop,
      family = gaussian(),
      chains = brms_chains,
      iter = brms_iter,
      cores = brms_cores,
      seed = brms_seed
    )
    save_model_outputs("eye_relsign4_irrelevant_prop_mixed", m_irr_prop)
  }
}

# ---------- 5) Fixation duration ~ relevance * position (fixation-level) ----------
# Tests whether log fixation duration varies by relevance and fixation position
# Data: output/choice_fixations_clean_buffer_50.csv (one row per fixation)
# Position binned: 1-6 individually, 7+ collapsed to 7, treated as continuous

excluded_subjects <- c("107", "131")

fix_path <- file.path(project_root, "output", "choice_fixations_clean_buffer_50.csv")
fix_df <- read_csv_if_exists(fix_path)

if (!is.null(fix_df)) {
  fix_df <- fix_df %>%
    filter(!subject_id %in% excluded_subjects)

  n_subjects <- n_distinct(fix_df$subject_id)
  message("  Fixdur by position: N subjects = ", n_subjects)
  stopifnot(n_subjects == 41)

  fix_df <- fix_df %>%
    filter(!is.na(fixation_duration), fixation_duration > 0) %>%
    mutate(
      log_duration = log(fixation_duration),
      position_bin = pmin(fixation_count, 7),
      subject_id = as.factor(subject_id)
    )

  message("  N fixations = ", nrow(fix_df))

  m_fixdur_pos <- brm(
    log_duration ~ relevance * position_bin +
      (relevance * position_bin | subject_id),
    data = fix_df,
    family = gaussian(),
    chains = brms_chains,
    iter = brms_iter,
    cores = brms_cores,
    seed = brms_seed,
    control = list(adapt_delta = 0.95)
  )
  save_model_outputs("fixdur_by_position_human", m_fixdur_pos)
}

# ---------- 6) Proportion relevant fixated ~ position (subject-level) ----------
# Tests whether the proportion of fixations landing on relevant locations
# is above chance (0.5) and how it changes across fixation positions.
# Matches the y-axis of Figure 4C ("Prop. relevant fixated").
# Data: same fixation-level CSV as model 5, aggregated per subject x position.
# Position binned: 1-6 individually, 7+ collapsed to 7, treated as continuous.

if (!is.null(fix_df)) {
  # Aggregate to per-subject per-position proportion of relevant fixations
  fix_prop_df <- fix_df %>%
    group_by(subject_id, position_bin) %>%
    summarise(
      prop_relevant = mean(relevance, na.rm = TRUE),
      n_fixations = n(),
      .groups = "drop"
    ) %>%
    mutate(
      delta_chance = prop_relevant - 0.5
    )

  n_subj_prop <- n_distinct(fix_prop_df$subject_id)
  message("  Fixprop by position: N subjects = ", n_subj_prop)
  stopifnot(n_subj_prop == 41)
  message("  N subject x position obs = ", nrow(fix_prop_df))

  m_fixprop_pos <- brm(
    delta_chance ~ 1 + position_bin + (1 + position_bin | subject_id),
    data = fix_prop_df,
    family = gaussian(),
    chains = brms_chains,
    iter = brms_iter,
    cores = brms_cores,
    seed = brms_seed,
    control = list(adapt_delta = 0.95)
  )
  save_model_outputs("fixprop_by_position_human", m_fixprop_pos)
}

# ---------- 7) Valence × decision × position (3-way, chance-corrected) --------
# Tests whether reward valence (positive vs negative) differentiates gaze
# allocation across fixation positions differently for take vs leave decisions.
# Figure 4G-H.
#
# Computes chance-corrected proportions from fixation-level data joined with
# recalled rewards, matching the trial-level chance correction used in models
# 1-4 (chance = n_items_in_category / 6).
#
# Model: delta ~ dec_c * valence_c * position + (dec_c + valence_c + position | subject_id)
# Contrast coding:
#   dec_c:     take = +0.5, leave = -0.5
#   valence_c: positive = +0.5, negative = -0.5
#   position:  numeric (1-7, with 7+ collapsed)

message("\n---------- 7) Valence x decision x position (3-way, chance-corrected) ----------")

# Join fixation data with recalled rewards
item_vals_path <- file.path(project_root, "output", "behavior", "stats", "item_values_df.csv")
item_vals <- read_csv_if_exists(item_vals_path)

if (!is.null(fix_df) && !is.null(item_vals)) {
  # fix_df already filtered to N=41 and has position_bin from model 5

  item_vals <- item_vals %>%
    mutate(subject_id = as.character(subject)) %>%
    select(subject_id, game, image, recalled_value)

  fix_val <- fix_df %>%
    mutate(game = as.integer(game)) %>%
    left_join(item_vals, by = c("subject_id", "game", "image"))

  # Keep only relevant fixations with non-zero recalled reward
  fix_rel <- fix_val %>%
    filter(relevance == 1,
           !is.na(recalled_value),
           recalled_value != 0) %>%
    mutate(valence_label = ifelse(recalled_value > 0, "positive", "negative"))

  # Compute trial-level item counts for chance
  # For each trial, count how many relevant items have positive/negative recalled reward
  trial_items <- fix_val %>%
    filter(relevance == 1, !is.na(recalled_value), recalled_value != 0) %>%
    distinct(subject_id, game, trial_number, option, image, recalled_value) %>%
    mutate(valence_label = ifelse(recalled_value > 0, "positive", "negative")) %>%
    group_by(subject_id, game, trial_number, option, valence_label) %>%
    summarise(n_items = n(), .groups = "drop")

  # Chance = n_items_in_category / 6 (same as trial-level models)
  trial_chance <- trial_items %>%
    mutate(chance = n_items / 6)

  # For each trial × position_bin: count fixations by valence, compute proportion
  trial_pos_counts <- fix_rel %>%
    group_by(subject_id, game, trial_number, option, position_bin, valence_label) %>%
    summarise(n_fix = n(), .groups = "drop")

  # Total fixations at each trial × position (all items, not just relevant)
  trial_pos_total <- fix_df %>%
    filter(!is.na(fixation_duration), fixation_duration > 0) %>%
    group_by(subject_id, game, trial_number, option, position_bin) %>%
    summarise(n_total = n(), .groups = "drop")

  # Build full grid: trial × position × valence
  grid <- tidyr::expand_grid(
    trial_pos_total %>% select(subject_id, game, trial_number, option, position_bin),
    valence_label = c("positive", "negative")
  ) %>%
    distinct()

  trial_pos_props <- grid %>%
    left_join(trial_pos_total,
              by = c("subject_id", "game", "trial_number", "option", "position_bin")) %>%
    left_join(trial_pos_counts,
              by = c("subject_id", "game", "trial_number", "option", "position_bin", "valence_label")) %>%
    left_join(trial_chance,
              by = c("subject_id", "game", "trial_number", "option", "valence_label")) %>%
    mutate(
      n_fix = tidyr::replace_na(n_fix, 0),
      chance = tidyr::replace_na(chance, 0),
      prop = n_fix / n_total,
      delta = prop - chance
    )

  # Add decision info from fixation data
  decision_info <- fix_df %>%
    distinct(subject_id, game, trial_number, option, choice)

  trial_pos_props <- trial_pos_props %>%
    left_join(decision_info,
              by = c("subject_id", "game", "trial_number", "option")) %>%
    filter(!is.na(choice))

  # Aggregate to subject × position × decision × valence
  subj_pos <- trial_pos_props %>%
    mutate(decision = ifelse(choice == 1, "take", "leave")) %>%
    group_by(subject_id, position_bin, decision, valence_label) %>%
    summarise(delta = mean(delta, na.rm = TRUE), .groups = "drop")

  n_subj_gh <- n_distinct(subj_pos$subject_id)
  message("  N subjects = ", n_subj_gh)
  stopifnot(n_subj_gh == 41)

  d_long <- subj_pos %>%
    mutate(
      dec_c = ifelse(decision == "take", 0.5, -0.5),
      valence_c = ifelse(valence_label == "positive", 0.5, -0.5),
      position = position_bin,
      subject_id = factor(subject_id)
    )

  message("  Positions: ", paste(sort(unique(d_long$position)), collapse = ", "))
  message("  Observations: ", nrow(d_long),
          "  |  Subjects: ", n_distinct(d_long$subject_id))

  m_valence_pos <- brm(
    delta ~ dec_c * valence_c * position +
      (dec_c + valence_c + position | subject_id),
    data = d_long,
    family = gaussian(),
    chains = brms_chains,
    iter = brms_iter,
    cores = brms_cores,
    seed = brms_seed,
    control = list(adapt_delta = 0.95)
  )
  save_model_outputs("valence_by_position_human", m_valence_pos)
} else {
  message("  SKIPPED model 7: fixation data or item_values_df.csv not found")
}

message("Eye-tracking mixed-effects model summaries saved to ", stats_dir)
